server:
  port: 23001
spring:
  application:
    name: consumer-23001
my:
  consumer:
    baseUrl: http://DEPT-PROVIDER



eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
